version: "3.9"
services:
  bagholder:
    build: ./docker
    container_name: bagholder
    ports:
      - "8012:8012"
    volumes:
      - ./app/data:/app/data
    restart: unless-stopped
    environment:
      - TZ=UTC
